update_fastlane
default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do

  end

  desc "Travis lane"
  lane :travis do
    xctool :clean, :build, [
      "--workspace", "Dodies.lv.xcworkspace",
      "--scheme", "Dodies.lv",
      "--configuration", "Debug",
      "CODE_SIGN_IDENTITY=\"\"",
      "CODE_SIGNING_REQUIRED=NO"
    ].join(" ")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    cert
    sigh

    increment_build_number

    gym(
      workspace: "Dodies.lv.xcworkspace",
      scheme: "Dodies.lv",
      clean: true,
      output_name: "Dodies.lv.ipa"
    )

    pilot(
      skip_submission: true
    )
  end

  lane :build do
    gym(
      workspace: "Dodies.lv.xcworkspace",
      scheme: "Dodies.lv",
      clean: true,
      output_name: "Dodies.lv.ipa",
      use_legacy_build_api: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Dodies.lv") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end
