update_fastlane
default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do

  end
  
  desc "Certs"
  lane :certificates do
    match(type: "appstore")
    match(type: "development")
  end

  desc "Travis lane"
  lane :travis do
    # xctool :clean, :build, [
    #   "--workspace", "Dodies.lv.xcworkspace",
    #   "--scheme", "Dodies.lv",
    #   "--configuration", "Debug",
    #   "CODE_SIGN_IDENTITY=\"\"",
    #   "CODE_SIGNING_REQUIRED=NO"
    # ].join(" ")
    
    # gym(
    #   clean: true,
    #   workspace: "Dodies.lv.xcworkspace",
    #   scheme: "Dodies.lv",
    #   configuration: "Debug",
    #   codesigning_identity: "",
    #   skip_build_archive: "NO"
    #   xcargs: "CODE_SIGNING_REQUIRED=NO"
    # )
    
    # xcodebuild(
    #   workspace: "Dodies.lv.xcworkspace",
    #   scheme: "Dodies.lv",
    #   configuration: "Debug",
    #   clean: true,
    #   build: true,
    #   build_settings: {
    #     "CODE_SIGNING_REQUIRED" => "NO",
    #     "CODE_SIGN_IDENTITY" => "",
    #     "CODE_SIGN_ENTITLEMENTS" => "",
    #     "CODE_SIGNING_ALLOWED" => "NO"
    #   }
    # )
    
    certificates
    sigh
    
    increment_build_number(
      build_number: Time.new.strftime("%Y%m%d.%H%M%S")
    )

    clear_derived_data

    # build
    gym(
			workspace: "Dodies.lv.xcworkspace",
			scheme: "Dodies.lv",
			clean: true,
			output_name: "Dodies.lv.ipa",
      verbose: true,
      toolchain: "com.apple.dt.toolchain.Swift_3_0")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    cert
    sigh

    increment_build_number

    gym(
      workspace: "Dodies.lv.xcworkspace",
      scheme: "Dodies.lv",
      clean: true,
      output_name: "Dodies.lv.ipa",
      include_symbols: true
    )

    dsym_zip

    copy_artifacts(
      target_path: 'artifacts',
      artifacts: ['*.dSYM.zip']
    )

    # crashlytics(
    #   api_token: "34be06edc6f733a743335744b07a23f6a3e5b344",
    #   build_secret: "a9207ff06b3417aa4bf8c6408432761ca87c5b52dca8f2365b133eea61d407cc",
    #   groups: "dodies",
    #   emails: ["fassko@gmail.com","normis@normis.info"], 
    #   notes: "Automatic iOS Build"
    # )
    
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  lane :release do
    cert
    sigh

    increment_build_number

    gym(
      workspace: "Dodies.lv.xcworkspace",
      scheme: "Dodies.lv",
      clean: true,
      output_name: "Dodies.lv.ipa",
      include_symbols: true
    )

    dsym_zip

    copy_artifacts(
      target_path: 'artifacts',
      artifacts: ['*.dSYM.zip']
    )

    deliver
  end

  lane :build do
    gym(
      workspace: "Dodies.lv.xcworkspace",
      scheme: "Dodies.lv",
      clean: true,
      output_name: "Dodies.lv.ipa",
      use_legacy_build_api: true
    )
  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end
